# This file is machine-generated - editing it directly is not advised

[[GroupSlices]]
git-tree-sha1 = "4de31f97ac545bf533eef17109725dfc68e29d64"
uuid = "d853e229-7c7c-56e9-b6be-9a1acc5f13d9"
version = "0.0.3"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[Requires]]
deps = ["UUIDs"]
git-tree-sha1 = "28faf1c963ca1dc3ec87f166d92982e3c4a1f66d"
uuid = "ae029012-a4dd-5104-9daa-d747884805df"
version = "1.1.0"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[StaticArrays]]
deps = ["LinearAlgebra", "Random", "Statistics"]
git-tree-sha1 = "016d1e1a00fabc556473b07161da3d39726ded35"
uuid = "90137ffa-7385-5640-81b9-e52037218182"
version = "0.12.4"

[[Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[divido]]
deps = ["GroupSlices"]
git-tree-sha1 = "771c3e29bd14ae6b39c8482b2ca7a4588f3c6588"
repo-rev = "master"
repo-url = "D:\\estragio\\PhD\\99_Github\\divido.jl"
uuid = "b366ad8f-a076-4708-9cec-a1a8bfa60877"
version = "0.1.0"

[[intrico]]
deps = ["Requires", "StaticArrays", "divido"]
git-tree-sha1 = "4aa00b6470d674057c83d087fb281ef9f162b26d"
repo-rev = "master"
repo-url = "D:\\estragio\\PhD\\99_Github\\intrico.jl"
uuid = "dfd82dbb-88c2-41fc-8dcc-71712229ae1e"
version = "0.1.0"
